export default[
  {
    numCompra: 0,
    buyer: "comprador0",
    date: "20/10/2017",
    productList: [{nombre: "Leche", sku: "3245235532", cantidad: 3}],
    totalPrice: 6000,
    discountCode: "",
    deliveryType: "Personal",
    deliverySent: false,
    deliveryAccepted: false,
    deliveryRejectedReason: "",
  },
  {
    numCompra: 1,
    buyer: "comprador0",
    date: "22/10/2017",
    productList: [{nombre: "Leche", sku: "3245235532", cantidad: 5}],
    totalPrice: 10000,
    discountCode: "",
    deliveryType: "Domicilio",
    deliverySent: true,
    deliveryAccepted: false,
    deliveryRejectedReason: "No fue lo que pedí.",
  },
  {
    numCompra: 2,
    buyer: "comprador1",
    date: "20/11/2017",
    productList: [{nombre: "Leche", sku: "3245235532", cantidad: 3}],
    totalPrice: 6000,
    discountCode: "",
    deliveryType: "Domicilio",
    deliverySent: false,
    deliveryAccepted: false,
    deliveryRejectedReason: "",
  },
  {
    numCompra: 3,
    buyer: "comprador0",
    date: "21/11/2017",
    productList: [{nombre: "Gaseosa", sku: "4637284121", cantidad: 2}],
    totalPrice: 12000,
    discountCode: "",
    deliveryType: "Domicilio",
    deliverySent: false,
    deliveryAccepted: false,
    deliveryRejectedReason: "",
  },
]
