export default[
  {
    numCompra: 0,
    buyer: "comprador0",
    date: "20/10/2017",
    productList: [{nombre: "Leche", sku: "3245235532", cantidad: 3}],
    totalPrice: 6000,
    discountCode: "",
    deliveryType: "CollectService",
    deliveryCost: 0,
    deliverySent: false,
    deliveryAccepted: false,
    deliveryRejectedReason: "",
  },
  {
    numCompra: 1,
    buyer: "comprador0",
    date: "22/10/2017",
    productList: [{nombre: "Leche", sku: "3245235532", cantidad: 5}],
    totalPrice: 10000,
    discountCode: "",
    deliveryType: "DeliveryService",
    deliveryCost: 5000,
    deliverySent: true,
    deliveryAccepted: false,
    deliveryRejectedReason: "No fue lo que pedí.",
  },
  {
    numCompra: 2,
    buyer: "comprador1",
    date: "20/11/2017",
    productList: [{nombre: "Leche", sku: "3245235532", cantidad: 3}],
    totalPrice: 6000,
    discountCode: "",
    deliveryType: "DeliveryService",
    deliveryCost: 5000,
    deliverySent: false,
    deliveryAccepted: false,
    deliveryRejectedReason: "",
  },
]
